#################################################################################################################
# Create a Ceph pool with settings for erasure coding. A minimum of 3 OSDs are required in this example.
#  kubectl create -f pool-ec.yaml
#
#  Origin: https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/pool-ec.yaml
#################################################################################################################

apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ec-pool
  namespace: openshift-storage
