#cloud-config

groups:
    - cephuser

users:
  - name: cephuser
    primary-group: cephuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

chpasswd:
  list: |
    root:passwd
    cephuser: cephuser
  expire: False


runcmd:
  - touch /ceph-qa-ready
  - sudo sed -i -e 's/^Defaults\s\+requiretty/# \0/' /etc/sudoers


final_message: "Ready for ceph qa testing"
